name: explo24
channels:
  - conda-forge
dependencies:
  - numpy=2.1.0
  - pandas=2.2.2
  - tqdm=4.66.5
  - jinja2=3.1.4
  - rapidfuzz=3.9.6 
  - tomlkit=0.13.2
  - ipython=8.26.0
  - python-Levenshtein=0.25.1
  - geopandas=1.0.1
  - py7zr=0.22.0
  - fiona=1.9.6
  - shapely=2.0.6
  - requests=2.31.0
  - plotly=5.21.0
  - scipy=1.14.0
  - cma=3.3.0
  - jupyter=1.0.0
  - pyarrow=17.0.0
  - xlrd=2.0.1
  - pip=24.2
  - pip:
    - biogeme==3.2.14
